# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               "Joseph Deferio"
tagline:             ""
description:         "Joseph Deferio"
baseurl:             ""
url:                 "http://jdeferio.github.io"
paginate:            5

# Pages
pages_list:
  Bio:               '/'
  Projects:          '/projects'
  Research:          '/research'
  UserGuide:         '/userguide'

# About
author:
  name:              "Joseph Deferio"
  email:             jdeferio.io@gmail.com

# Custom vars
version:             1.0.0

# Social
minima:
  social_links:
    github: jdeferio
    stackoverflow: "3299050"
    linkedin: joseph-j-deferio

# plugins:             [exifr]
